services:
  - type: web
    name: bento-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_PATH
        value: /app/data/db.sqlite
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false

